(function(){"use strict";
  const key="co-di-dien-visual-v1";
  const regions=[{id:"trung_vuc",name:"Trung Vực",danger:2,desc:"Linh mạch và tông môn hội tụ."},{id:"dong_hoang",name:"Đông Hoang",danger:4,desc:"Yêu sơn kéo dài dưới tán rừng cổ."},{id:"tay_mac",name:"Tây Mạc",danger:3,desc:"Sa hải che giấu những thành trì mất tên."},{id:"nam_chuong",name:"Nam Chướng",danger:4,desc:"Độc chướng và linh dược cùng sinh."},{id:"bac_nguyen",name:"Bắc Nguyên",danger:3,desc:"Băng nguyên lưu giữ ký ức cổ tộc."},{id:"vo_tan_hai",name:"Vô Tận Hải",danger:5,desc:"Biển không có đường chân trời."},{id:"thien_khong_vuc",name:"Thiên Không Vực",danger:6,locked:true,desc:"Chỉ cao giai mới đặt chân tới."},{id:"u_minh_gioi",name:"U Minh Giới",danger:7,locked:true,desc:"Khe nứt sang nơi người chết không ngủ."}];
  const realmNames=["Di Mệnh Cảnh","Khai Lộ Cảnh","Dựng Thai Cảnh","Kim Ấn Cảnh","Anh Linh Cảnh","Thần Tính Cảnh","Hư Giới Cảnh","Hợp Đạo Cảnh"]; const fates=[{name:"Vạn Đạo",grade:"Hoàng Phẩm",score:10,desc:"Bàng môn tả đạo có muôn vàn con đường; giúp mệnh nhân đi thông những lối không chính thống."},{name:"Tĩnh Thủy",grade:"Phàm Phẩm",score:6,desc:"Tâm như mặt nước trước gió, giảm dao động khi vận công."},{name:"Dị Đồng",grade:"Huyền Phẩm",score:18,desc:"Con mắt nhìn thấy đường viền của những thứ thế gian cố che giấu."}];
  const techniques=[{name:"Dẫn Khí Nhập Môn",type:"Tâm pháp",desc:"Thu nạp linh khí chậm nhưng ổn định."},{name:"Kiếm Khí Sơ Cấp",type:"Chiến đấu",desc:"Ngưng linh lực thành một đường kiếm ngắn."}];
  let state=load()||{name:"Vô Danh",region:"trung_vuc",realm:0,exp:0,hp:100,maxHp:100,san:100,maxSan:100,fortune:45,phy:12,mag:12,turn:1,log:[]};
  const $=id=>document.getElementById(id); function save(){localStorage.setItem(key,JSON.stringify(state));$("save-state").textContent="Đã lưu lúc "+new Date().toLocaleTimeString();} function load(){try{return JSON.parse(localStorage.getItem(key)||"null")}catch(e){return null}}
  function add(text,kind="system"){state.log.push({text,kind});if(state.log.length>80)state.log.shift();render();} function region(){return regions.find(x=>x.id===state.region)||regions[0]}
  function render(){ $("name").textContent=state.name;$("realm").textContent=realmNames[state.realm]||"Đạo Ngoại Cảnh";$("hp").textContent=Math.round(state.hp)+"/"+state.maxHp;$("san").textContent=Math.round(state.san)+"/"+state.maxSan;$("exp").textContent=state.exp;$("phy").textContent=state.phy;$("mag").textContent=state.mag;$("fortune").textContent=state.fortune<50?"Phàm Nhân Khí Vận":state.fortune<75?"Tiểu Thiên Kiêu":"Yêu Nghiệt Chi Tư";$('hp-bar').style.width=Math.max(0,state.hp/state.maxHp*100)+"%";$('san-bar').style.width=Math.max(0,state.san/state.maxSan*100)+"%";const active=document.querySelector('.tab.active').dataset.tab;panel(active);save();}
  function panel(tab){const p=$("panel"),a=$("actions");a.innerHTML="";if(tab==="story"){p.innerHTML='<div class="story-log">'+(state.log.length?state.log.map(x=>'<div class="story-entry '+x.kind+'">'+x.text+'</div>').join(""):"<div class=story-entry>Gió thổi qua Vạn Giới Lộ. Một thứ gì đó ở rất xa vừa mở mắt.</div>")+'</div><div class="command-line"><span>›</span><input id="command" placeholder="Thử: tu luyện, đi đông, quan sát..."><button id="command-submit" class="button">Gửi</button></div>';[["Tu luyện",cultivate],["Bế quan 1 giờ",()=>secluded(1)],["Quan sát",look],["Đi Đông",()=>travel("dong_hoang")],["Nghỉ ngơi",rest]].forEach(([label,fn])=>button(a,label,fn));$("command-submit").onclick=()=>command($("command").value);$("command").onkeydown=e=>{if(e.key==="Enter")command(e.target.value)};}else if(tab==="map"){p.innerHTML='<h3>Bản đồ Vạn Giới Lộ</h3><p class=muted>Vùng nguy hiểm hơn mở ra cùng cảnh giới và cái giá phải trả.</p><div class=map>'+regions.map(r=>'<div class="region '+(r.id===state.region?"current ":"")+(r.locked?"locked":"")+'" data-region="'+r.id+'"><b>'+r.name+'</b><small>Nguy hiểm '+r.danger+'/7<br>'+r.desc+'</small></div>').join("")+'</div>';p.querySelectorAll('[data-region]').forEach(el=>el.onclick=()=>travel(el.dataset.region));}else if(tab==="fate"){p.innerHTML='<h3>Tử Vi Mệnh Số</h3><p class=muted>Mỗi mệnh số là một mảnh ký ức không thuộc về người đang mang nó.</p><div class=fate-grid>'+fates.map(f=>'<article class=fate><b>'+f.name+'</b><small>'+f.grade+' · Cát · '+f.score+' điểm</small><p>'+f.desc+'</p></article>').join("")+'</div>';}else{p.innerHTML='<h3>Công pháp</h3><p class=muted>Tu luyện nhận Tu vi và Độ thông thạo. Chiến đấu chỉ tăng thông thạo công pháp chiến đấu.</p><div class=technique-grid>'+techniques.map(t=>'<article class=technique><b>'+t.name+'</b><small>'+t.type+'</small><p>'+t.desc+'</p></article>').join("")+'</div>';}}
  function button(parent,label,fn){const b=document.createElement("button");b.className="action";b.textContent=label;b.onclick=fn;parent.appendChild(b)}
  function cultivate(){state.turn++;const gain=8+Math.floor(Math.random()*8)+state.mag;state.exp+=gain;state.san=Math.max(0,state.san-2);add("Ngươi nuốt một sợi linh khí méo mó. Tu vi +"+gain+"; Thanh Tỉnh -2.");if(state.san===0)add("Thần thức vỡ vụn. Tha Hóa đang nhìn qua mắt ngươi.","warn")}
  function secluded(hours){const h=Math.max(1,Math.min(8,Number(hours)||1));if(region().danger>3){add("Nơi này không đủ an toàn để bế quan.","warn");return}for(let i=0;i<h*3;i++)cultivate();add("Bế quan kết thúc. Ngươi không chắc thời gian đã trôi qua đúng như vậy.");}
  function rest(){state.san=Math.min(state.maxSan,state.san+14);state.hp=Math.min(state.maxHp,state.hp+20);add("Ngươi khép mắt. Khi mở ra, một chiếc bóng vẫn đứng ở góc phòng.")}
  function travel(id){const target=regions.find(r=>r.id===id);if(!target)return;if(target.locked&&state.realm<6){add("Thiên cơ khép lại con đường tới "+target.name+". Cần cảnh giới cao hơn.","warn");return}state.region=id;state.turn++;state.san=Math.max(0,state.san-target.danger);add("Ngươi tiến vào "+target.name+". Thanh Tỉnh -"+target.danger+".");}
  function look(){add("Ngươi đang ở "+region().name+". "+region().desc+" Có một cảm giác rằng bản đồ vừa đổi chỗ.")}
  function command(raw){const t=String(raw||"").trim().toLowerCase();if(t.includes("tu luyện")){cultivate();return}if(t.includes("bế quan")){secluded((t.match(/\d+/)||[1])[0]);return}if(t.includes("nghỉ")){rest();return}if(t.includes("quan sát")||t.includes("nhìn")){look();return}if(t.includes("đông")){travel("dong_hoang");return}add("Vạn Giới Lộ không hiểu mệnh lệnh ấy.","warn")}
  document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");render()});$("save").onclick=save;$("reset").onclick=()=>{localStorage.removeItem(key);location.reload()};render();
})();
