"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const realmPath = path.join(ROOT, "data", "canh_gioi_tien_hiep.json");
const factionPath = path.join(ROOT, "data", "tu_tien_factions.json");
const outputPath = path.join(ROOT, "data", "world_data.js");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function readRealmSource() {
  if (fs.existsSync(realmPath)) return readJson(realmPath);
  if (!fs.existsSync(outputPath)) throw new Error("Không tìm thấy canh_gioi_tien_hiep.json hoặc js/world_data.js.");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(outputPath, "utf8"), sandbox, { filename: outputPath });
  const cultivationData = sandbox.window.CULTIVATION_DATA;
  if (!Array.isArray(cultivationData?.realms)) throw new Error("js/world_data.js không chứa CULTIVATION_DATA hợp lệ.");
  fs.writeFileSync(realmPath, `${JSON.stringify(cultivationData, null, 2)}\n`, "utf8");
  return cultivationData;
}

function validate(realms, factions) {
  const realmList = Array.isArray(realms) ? realms : realms.realms;
  if (!Array.isArray(realmList) || realmList.length < 10) {
    throw new Error("canh_gioi_tien_hiep.json phải có ít nhất 10 cảnh giới.");
  }
  const realmIds = new Set(realmList.map((realm) => realm.id));
  const legacyRealmIds = new Set(realmList.flatMap((realm) => realm.legacyIds || realm.legacy_ids || []));
  if (realmIds.size !== realmList.length) throw new Error("ID cảnh giới bị trùng.");

  const regions = factions.world?.regions || [];
  const regionIds = new Set(regions.map((region) => region.id));
  if (!regions.length || regionIds.size !== regions.length) throw new Error("Dữ liệu khu vực trống hoặc trùng ID.");

  const factionIds = new Set();
  (factions.factions || []).forEach((faction) => {
    if (factionIds.has(faction.id)) throw new Error(`ID thế lực bị trùng: ${faction.id}`);
    factionIds.add(faction.id);
    if (!regionIds.has(faction.region_id)) throw new Error(`Thế lực ${faction.id} trỏ tới khu vực không tồn tại.`);
    const realmKey = faction.highest_realm;
    const hasRealm = realmIds.has(realmKey) || legacyRealmIds.has(realmKey) || realmList.some((realm) => realm.id.startsWith(`${realmKey}_`));
    if (!hasRealm) throw new Error(`Thế lực ${faction.id} có cảnh giới không tồn tại.`);
  });
  (factions.world?.routes || []).forEach(([from, to]) => {
    if (!regionIds.has(from) || !regionIds.has(to)) throw new Error(`Tuyến đường không hợp lệ: ${from} - ${to}`);
  });
  if (!Array.isArray(factions.guilds) || factions.guilds.length !== 150) {
    throw new Error("tu_tien_factions.json phải có đúng 150 môn phái.");
  }
  factions.guilds.forEach((guild) => {
    if (!regionIds.has(guild.region_id)) throw new Error(`Môn phái ${guild.id} trỏ tới khu vực không tồn tại.`);
  });
}

function main() {
  const realmSource = readRealmSource();
  const factions = readJson(factionPath);
  validate(realmSource, factions);
  const realms = Array.isArray(realmSource) ? realmSource : realmSource.realms;
  const cultivationData = { schema_version: 1, source: "canh_gioi_tien_hiep.json", realms };
  const content = [
    "/* AUTO-GENERATED by tools/generate_world_data.js — do not edit directly. */",
    `window.CULTIVATION_DATA = ${JSON.stringify(cultivationData)};`,
    `window.FACTION_DATA = ${JSON.stringify(factions)};`,
    `window.GUILD_DATA = ${JSON.stringify({ tiers: factions.guild_tiers, guilds: factions.guilds })};`,
    ""
  ].join("\n");
  fs.writeFileSync(outputPath, content, "utf8");
  console.log(`Generated ${path.relative(ROOT, outputPath)} (${realms.length} realms, ${factions.factions.length} factions, ${factions.guilds.length} guilds)`);
}

main();
