/* M41-M49/B.1/FT9 map, fog, weather, coordinate and travel producer matrix. */
const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const root = __dirname + '/..';
const context = { console, Math, Date, structuredClone: global.structuredClone };
context.window = context;
vm.createContext(context);
for (const file of ['data/data.js', 'data/fate_data.js', 'data/expansion_data.js', 'data/fate_relationships.js', 'data/path_fate_relations.js', 'js/i18n.js', 'js/engine.js', 'js/expansion.js']) {
  vm.runInContext(fs.readFileSync(root + '/' + file, 'utf8'), context, { filename: file });
}
const E = context.GameEngine, X = context.GameExpansion;
const state = E.createState('map-producer-matrix');
X.ensureExpansionState(state);
const locations = E.locationPool(state);
const from = state.locationId;
const to = Object.values(locations[from]?.exits || {})[0];
assert(from && to, 'map route fixture missing');
X.mapNode(state, from);
X.mapNode(state, to);
const coords = E.nodeCoordinates(state, from);
assert(coords && Number.isFinite(coords.x) && Number.isFinite(coords.y), 'canonical coordinate producer missing');
const first = X.mapInfluenceSnapshot(state, from);
assert(first && first.nodeId === from && Number.isFinite(first.pressure) && first.influenceMap, 'influence producer incomplete');
const revision = state.mapState.influenceRevision;
const eventFaction = Object.keys(state.worldSimulation.factionState || {})[0] || context.GameData.WORLD_MAP?.factions?.[0]?.id || 'fixture_faction';
assert(eventFaction, 'map faction fixture missing');
assert(X.recordMapEventInfluence(state, from, eventFaction, 20, E.gameDayOrdinal(state) + 5).success, 'map event influence producer rejected fixture');
const second = X.mapInfluenceSnapshot(state, from);
assert(state.mapState.influenceRevision > revision, 'influence cache did not invalidate on event producer');
assert(state.mapState.eventInfluence[from][eventFaction].score === 20, 'event influence producer was not persisted');
assert(X.mapFogState(state, from, 0) === 0 && X.mapFogState(state, from, 3) === 3, 'fog levels not bounded/canonical');
assert(X.mapFogState(state, from) === 3, 'fog read path failed');
const weight = X.travelWeightSnapshot(state, to);
assert(weight.source === 'canonical_travel_weight' && Number.isFinite(weight.weatherWeight) && Number.isFinite(weight.terrainWeight), 'travel weight matrix incomplete');
const blockedFast = X.travelPlan(state, from, to, 'truyền_tống_trận');
assert(!blockedFast.success && blockedFast.reason, 'fast-travel exposed an unregistered target');
const plan = X.travelPlan(state, from, to, 'walk');
assert(plan.success && plan.fromNodeId === from && plan.toNodeId === to, 'travel plan producer failed');
state.visitedLocations = Array.from(new Set([...(state.visitedLocations || []), from, to]));
X.mapNode(state, to).role = 'thành';
state.mapState.fastTravel[from] = true;
state.mapState.fastTravel[to] = true;
const fastPlan = X.travelPlan(state, from, to, 'truyền_tống_trận');
assert(fastPlan.success && fastPlan.fromNodeId === from && fastPlan.toNodeId === to && fastPlan.gameDays === 0, 'fast-travel producer contract failed');
assert(fastPlan.disclosure?.source && fastPlan.disclosure?.destination, 'fast-travel disclosure omitted source/destination');
const eligibleNodes = Object.keys(locations).filter((nodeId) => X.travelPlan(state, from, nodeId, 'truyền_tống_trận').success);
assert(eligibleNodes.includes(to), 'eligible fast-travel target matrix lost registered target');
assert(!eligibleNodes.includes(from), 'fast-travel allowed self-target without movement');
const started = X.startTravel(state, to, 'walk');
assert(started.success && state.travelTask && state.travelTask.expectedMapVersion === state.mapState.version, 'travel task/version contract failed');
const snapshot = X.travelTaskSnapshot(state);
assert(snapshot.status === state.travelTask.status && snapshot.toNodeId === to, 'travel snapshot disclosure failed');
assert(X.interruptTravel(state).success, 'travel interrupt failed');
assert(X.resumeTravel(state).success, 'travel resume failed');
assert(X.cancelTravel(state).success, 'travel cancel failed');
const commandTravel = X.runExpansionCommand(state, 'travel_fast', to);
assert(commandTravel.success && state.travelTask?.travelType === 'truyền_tống_trận', 'fast-travel UI command bridge failed');
assert(['cancelled', 'completed'].includes(state.travelTask?.status) || X.cancelTravel(state).success, 'fast-travel command cleanup failed');
assert(X.validateMapCanonicalState(state).ok && X.validateMapCoordinates(state).valid, 'map canonical validators failed');
console.log('OK: map producer matrix (influence/cache, fog, weather travel weight, coordinates, travel task/version/disclosure)');
